### ISSUE TITLE
Forbid certain names from being imported

### ISSUE THREAD

**Issue by flying-sheep** [seddonym/import-linter#113]
Due to [PEP 585](https://www.python.org/dev/peps/pep-0585/) (Making builtin collections and `collections.abc` classes generic) and [PEP 428](https://www.python.org/dev/peps/pep-0428/) (pathlib), a lot of names in the stdlib shouldn’t be used anymore, while the modules themselves still have their uses, e.g.

- `typing.Tuple[...]` → `tuple[...]`
- `typing.Collection[...]` → `collections.abc.Collection[...]`
- `os.path.abspath()` → `Path.resolve()`
- `os.stat()` → `Path.stat()`, `Path.owner()`, `Path.group()`
- …¹

It would be great to be able to express those deprecations using import-linter

¹The compatibility tables can be found here: [generics](https://www.python.org/dev/peps/pep-0585/#implementation) and [pathlib](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module)

**Comment by meshy** [comment]
I think the `Tuple` -> `tuple` might be picked up by https://github.com/asottile/pyupgrade

Perhaps the others might make sense there too?

**Comment by seddonym** [comment]
Thanks for the suggestion! I'm going to close it, but here's why.

Import Linter is designed to lint the import graph of modules. It's more focused on the relationships between modules as a way of encouraging a user-defined architecture. I don't think it should be expanded to cover linting of specific objects. That might be better suited to a flake8 plugin perhaps?

If you wanted to prevent the importing of, say, `typing`, you can of course use a [forbidden contract](https://import-linter.readthedocs.io/en/stable/contract_types.html).

I appreciate the suggestion anyway and feel free to open further issues. 😄

**Comment by flying-sheep** [comment]
Sure! Preventing scope creep is a good thing!
