### ISSUE TITLE
Include a `py.typed` marker in package

### ISSUE THREAD

**Issue by flaeppe** [seddonym/import-linter#128]
It seems type annotations are in place (or is there some stuff lacking?), so it'd be nice if `py.typed` was included so that type checkers could recognise the annotations. Would be helpful to have when writing custom contracts.

Ref: [PEP 561](https://peps.python.org/pep-0561/)

**Comment by seddonym** [comment]
Thanks for bringing this to my attention, I wasn't aware of py.typed. Good idea, feel free to do a PR, otherwise I'll get around to it soon.

**Comment by flaeppe** [comment]
I've just opened #129
