### ISSUE TITLE
Can't handle a file with a dot in it

### ISSUE THREAD

**Issue by mangelozzi** [seddonym/import-linter#140]
In my project I have an eample configuration file called: `src/config/cfg1_custom.example.py`. It is present as an example template file.
The user of project will copy this file to `src/config/cfg1_custom.py` and fille out the relevant section.

However when I try run import linter it errors out with:
```
Could not find module src.config.cfg1_custom.example.
```

Maybe the solution is to add a ignore paramter to the [top-level-configuration](https://import-linter.readthedocs.io/en/stable/usage.html#top-level-configuration) ?

**Comment by seddonym** [comment]
Thanks for raising the issue.

Could you provide your Import Linter configuration file?

**Comment by mangelozzi** [comment]
> Thanks for raising the issue.
> 
> Could you provide your Import Linter configuration file?

Sure, I am still trying to set it up, so its just this at the moment:

```python
[importlinter]
root_package = src

[importlinter:contract:1]
name = lib only imports from python standard lib
type = independence
modules =
    src.lib.colorlib
```

**Comment by seddonym** [comment]
Thanks.

Modules with dots in the name aren't valid Python modules so I think the behaviour should just be to treat them as if they're not part of the project. I don't think you should need to put them in ignored imports.

This needs to be fixed in Grimp, ticket added here: https://github.com/seddonym/grimp/issues/95

(Incidentally, an independence contract with only one module is meaningless :) )

**Comment by mangelozzi** [comment]
> Thanks.
> 
> Modules with dots in the name aren't valid Python modules so I think the behaviour should just be to treat them as if they're not part of the project. I don't think you should need to put them in ignored imports.
> 
> This needs to be fixed in Grimp, ticket added here: [seddonym/grimp#95](https://github.com/seddonym/grimp/issues/95)
> 
> (Incidentally, an independence contract with only one module is meaningless :) )

I think ignoring file with a dot in their name sounds like a good solution!

**Comment by seddonym** [comment]
1.9.0 is now released, so this should be fixed.
