### ISSUE TITLE
Remove ImportGraph protocol

### ISSUE THREAD

**Issue by mwgamble** [seddonym/import-linter#148]
I've just submitted this PR to improve the typing of Grimp:

https://github.com/seddonym/grimp/pull/103

If it's merged and released, I won't be able to take advantage of it in my import-linter plugin straight away. That's because of this layer of indirection:

https://github.com/seddonym/import-linter/blob/master/src/importlinter/domain/ports/graph.py

If the upstream type was used directly, there wouldn't be any delays at all.

This is problematic in other ways too. For example, in the plugin I'm developing, I want to take advantage of two graph methods `find_downstream_modules` and `find_upstream_modules` that are provided by Grimp:

- https://github.com/seddonym/grimp/blob/master/src/grimp/application/ports/graph.py#L172
- https://github.com/seddonym/grimp/blob/master/src/grimp/application/ports/graph.py#L197

However, these aren't passed through in this package's indirection layer. This forces me to use some unfortunate hackery to convince the type-checker that yes actually the graph object I've been supplied is in fact a Grimp graph object.

So I'm curious - would you be amenable to dropping this indirection layer, perhaps as part of a v3?

**Comment by seddonym** [comment]
Thanks for raising this. I thinik you're right, there isn't much (any?) value in that layer of indirection. Feel free to submit a PR, otherwise I'll probably get around to it.

**Comment by seddonym** [comment]
This is now merged to master, thanks again for the suggestion.
