### ISSUE TITLE
Forbidden import checking doesn't work correctly for descendants, when allow_indirect_imports=true

### ISSUE THREAD

**Issue by seddonym** [seddonym/import-linter#196]
Noticed by @qasimk. The contract will only check the source/forbidden modules, not their descendants.

This has been a bug since allow_indirect_imports was introduced, apologies for this.

**Comment by seddonym** [comment]
This fix is now available in version 12.1.0, enjoy!

**Comment by QasimK** [comment]
Thanks @seddonym :smile:
