### ISSUE TITLE
Question: Do not allow any imports

### ISSUE THREAD

**Issue by kkirsche** [seddonym/import-linter#223]
👋  Thanks for the great library!

I was wondering if I was missing something, but is there a simple contract type to simply say this module should not import any other module? For example, a module of constants? This avoids the need for having to define all the modules that are within a project.

Thanks, and sorry if this is a dumb question. I appreciate your time and help.

**Comment by seddonym** [comment]
Hi! Not a dumb question at all!

There is an open ticket for that and indeed [a pull request](https://github.com/seddonym/import-linter/pull/222) submitted by @sbrugman. I have left comments but unfortunately it seems to have gone stale.

In the meantime you could look at a [layers contract](https://import-linter.readthedocs.io/en/v2.0/contract_types.html#layers) with that module being the lowest layer. You'd have to explicitly list the other sibling modules though. You could also do it with not too much code as [a custom contract](https://import-linter.readthedocs.io/en/v2.0/contract_types.html#custom-contract-types). Or - even simpler - just `grep` for the work `import` in a completely custom script!
