### ISSUE TITLE
Similar issue on Windows as for `layer-linter`

### ISSUE THREAD

**Issue by SimonBiggs** [seddonym/import-linter#42]
Currently getting the same error as `layer-linter` got initially on Windows.

```
Missing layer in container 'pymedphys.coll': module pymedphys.coll._level1 does not exist
```

Could there be an issue with Windows path separator as before?

**Comment by seddonym** [comment]
Hi Simon, thanks for this - I didn't realise I wasn't getting notifications on this repo so I've only just seen the message. I'll look into it.

**Comment by SimonBiggs** [comment]
Also, I've decided to move away from limiting the levels and instead visually display them, allow them to change, just require it to be explicit in the commits. And also run CI verifying that there aren't any cycles at each level of abstraction.

See the graphs I am now producing for PyMedPhys:

https://pymedphys.com/developer/dependencies.html

**Comment by seddonym** [comment]
Oh cool - I'd be interested to know how you produce the graphs. One of the design features of importlinter is that it split off the import analysis from the linting - so there is a Python API to allow you to build / analyse graphs, if that's helpful - it's called [Grimp](https://grimp.readthedocs.io). Also, there's a CLI which actually draws the graphs called [Impulse](https://impulse-cli.readthedocs.io), though it could do with a bit more functionality.

Anyway thanks for the bug report, it's a problem with Grimp which I should be able to fix shortly.

**Comment by seddonym** [comment]
Ok I believe this should now be fixed in the latest version of import linter. If you have a chance, would you mind checking it's fixed it? (If not, don't worry - I understand if you're not using the library any more.)

**Comment by SimonBiggs** [comment]
Networks and graphviz were the tools I used to create the graphs. The code smells a bit at the moment, but the file parsing was done here:

https://github.com/pymedphys/pymedphys/blob/master/packages/pymedphys_monomanage/src/pymedphys_monomanage/parse/imports.py

Tree building done here:

https://github.com/pymedphys/pymedphys/blob/master/packages/pymedphys_monomanage/src/pymedphys_monomanage/tree/build.py

Graph drawing here:

https://github.com/pymedphys/pymedphys/blob/master/packages/pymedphys_monomanage/src/pymedphys_monomanage/draw/files.py

Designed to actually also support auto propagation of dependencies to the install requires of each package:

https://github.com/pymedphys/pymedphys/blob/master/packages/pymedphys_analysis/src/pymedphys_analysis/_install_requires.py

Plan is to make an easy to manage python Monorepo with a large number of python packages within the one repository.

**Comment by seddonym** [comment]
Very cool! Thanks.

**Comment by SimonBiggs** [comment]
:) you're more than welcome :)
