### ISSUE TITLE
Errors aren't outputted to users

### ISSUE THREAD

**Issue by seddonym** [seddonym/import-linter#57]
This PR indicates that errors are not always output to users' consoles: https://github.com/seddonym/import-linter/issues/55

I haven't been able to reproduce this myself yet.

**Comment by sobolevn** [comment]
One more related issue:

```python
# test.py

from someimport other  # missing space between some and `import`

...
```

And when I run `lint-imports` that's what I see:

```
» lint-imports                 
invalid syntax (<unknown>, line 9)
```

I have spent some time refactoring `.importlinter` config file 😆

**Comment by seddonym** [comment]
Thanks for this - I reckon this is a slightly different issue, I've created a separate ticket here: https://github.com/seddonym/import-linter/issues/57

**Comment by seddonym** [comment]
I'm going to close this due to lack of activity. Feel free to open again if anyone is able to help me reproduce the problem.
