### ISSUE TITLE
Forbidden contracts should support self forbidding

### ISSUE THREAD

**Issue by seddonym** [seddonym/import-linter#58]
A potential use case for a forbidden contract is along these lines:

```
[importlinter]
root_package = tests

[importlinter:contract:tests-restrictions1]
name = Explicit import restrictions for tests
type = forbidden
source_modules =
  tests
forbidden_modules =
  tests
```

Perhaps this contract should prevent any module within tests importing any other module within tests. Currently, it will fail with the error 'Modules have shared descendants.' This is because it's trying to see if any direct imports exist between the two packages, and Grimp thinks that doesn't make sense.

**Comment by AIGeneratedUsername** [comment]
Another real use case:
```
my_project/
    deploy/
    src/
    tests/
```
1. 'deploy' and 'tests' can do `from src import something`
2. In the 'src/' directory all imports **must be relative**, e.g. `from ..foo import bar`.

Currently, I see no way to forbid absolute imports inside a specific directory.

**Comment by seddonym** [comment]
Thanks for the comment!

From what I understand, you'd like to enforce _the way in which the import is written_ (i.e. relative rather than absolute). I don't think Import Linter is the right tool for this job, as it's more focused on _the relationships between modules_. That's not going to change based on whether it's absolute or relative.

It shouldn't be too difficult to write your own linter just to check that no lines begin with `from src` or `import src.`. Perhaps a custom flake8 plugin?
