### ISSUE TITLE
Better reporting of syntax errors in code

### ISSUE THREAD

**Issue by seddonym** [seddonym/import-linter#62]
If the code under analysis has a syntax error, the output of `lint-imports` is a bit unclear.

For example:

# test.py

from someimport other  # missing space between some and `import`

...
And when I run lint-imports that's what I see:

» lint-imports                 
invalid syntax (<unknown>, line 9)

Thanks @sobolevn for reporting this.

**Comment by blopker** [comment]
Ran into this issue too. Looks like just showing the full stacktrace instead of converting the exception into a str works pretty well.

**Comment by seddonym** [comment]
This is now fixed on master via this PR, https://github.com/seddonym/import-linter/pull/78.

The message now shows something like:
```
Syntax error in /path/to/module.py, line 1: fromi import b
```

Note, if you want to see the full stacktrace (which to be honest is probably not going to be that helpful in this case) you can run `lint-imports --debug`.
