### ISSUE TITLE
Complexity contract

### ISSUE THREAD

**Issue by sobolevn** [seddonym/import-linter#68]
Hi, @seddonym! 

I have an idea about the new contract type: package complexity. I am not sure about the technical part of this issue, but here's the motivation.

```ini
[importlinter:contract:grouped-modules]
name = We ensure that all modules are properly grouped
type = complexity

source_modules =
  wemake_python_styleguide

max_complexity = 5
```

What do we do here? When a package has more than `5` modules, we raise a violation. Why do we need it? Because this allows users to better group their modules together. And not just leave them in the main package with like 15  slightly-related files.

I guess, that it is a good fit for this project. And what do you think?

**Comment by seddonym** [comment]
Hi Nikita,

Thanks for the idea!

This wouldn't be *that* difficult to achieve with import linter, but I'm not yet convinced it should make its way into the core library.

If you think this would be valuable, I suggest you make it as a [custom contract type](https://import-linter.readthedocs.io/en/latest/custom_contract_types.html). You could then potentially release this as a separate Pypi package that could be installed if people want that feature.

Let me know if you need any guidance on how to do that - I'd be happy to review what you create. In the meantime I'm going to close this issue as I don't think it's right for core import-linter (yet!)
