### ISSUE TITLE
Duplicate ignored_imports lead to confusing error

### ISSUE THREAD

**Issue by seddonym** [seddonym/import-linter#69]
If you include an ignored import twice in a contract, you get the following error (as it tries to remove it the second time):

```
The edge mypackage.foo-mypackage.bar not in graph.
```

**Comment by skarzi** [comment]
hello :wave: 
can I prepare PR for this issue?
Do you prefer to add some option to `ListField` e.g. `drop_duplicates` and simply drop duplicates during parsing or some new field?

**Comment by seddonym** [comment]
Hi Łukasz,

Thanks so much for the high-quality pull request!

I really appreciate the work you've done so far, but I have concerns with adding this to `ListField`. Instead, as you suggest, I think we should have a totally new field: `SetField`.

`SetField` would be similar to`ListField`, but it would wrap a Python set, which means ordering wouldn't be important, and there wouldn't be duplicates. Then we could change `IndependenceContract` and `LayersContract` to use `SetField` instead, for their `ignore_imports`. This feels like a cleaner approach, as ordering (and duplicates) aren't important in `ignore_imports`. I also think the concepts of lists and sets are well understood, and it doesn't involving comprehending a subtly new type of data structure.

What do you think? I'm open to counter arguments.

**Comment by skarzi** [comment]
Sure I agree with you :+1:  In fact the only argument I had against adding `drop_duplicates` to `ListField` is that I don't know whole code well, so I was afraid that ordering must be preserved to not break anything. If ordering is unimportant then I can add `SetField` and fix all tests that have assertion which require ordering

**Comment by seddonym** [comment]
Awesome, thanks Łukasz - looking forward to seeing the PR.
