### ISSUE TITLE
Add topics for this repository

### ISSUE THREAD

**Issue by thedrow** [seddonym/import-linter#74]
I'm probably going to forget about this entirely by the time I'll need to implement this in my project.
It'd be easier to find this project if it had topics such as `linter`, `python` etc.

**Comment by seddonym** [comment]
Thanks for the issue!

I assume you're talking about PyPI topics. I'd be happy to add 'linter' but it seems like 'Python' might be redundant as a topic, no?

**Comment by thedrow** [comment]
Both PyPi and [Github topics](https://github.blog/2017-01-31-introducing-topics/) are useful.
It depends on where you search on.

**Comment by seddonym** [comment]
Cool, added to Github. I'll add them on PyPi at some point too.

**Comment by seddonym** [comment]
I've just looked at PyPI and it doesn't look like 'linter' is a valid topic. I've added them to Github though, so closing this issue.
