### ISSUE TITLE
Forbidden Contracts: Only Forbid Direct Imports

### ISSUE THREAD

**Issue by Skylion007** [seddonym/import-linter#91]
I was wondering if these was a way to configure the Forbidden Contract to only forbid direct imports. Perhaps with a boolean flag. This would be quite useful instead of having to add all the indirect imports to ignore imports directly. In this case, I want to allow indirect imports to a module, but only allow indirect imports. I want to forbid direct imports.

**Comment by seddonym** [comment]
I think this is a great idea. Feel free to submit a PR for it - you could also experiment with creating, for your own purposes, a [custom contract type](https://import-linter.readthedocs.io/en/stable/custom_contract_types.html).

**Comment by Skylion007** [comment]
@seddonym PR is open and passing CI tests now. 👍
